name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2

      - run: npm run checks
      - run: npm run build:actions

      - if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: EndBug/add-and-commit@v7
