name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./actions/exec-task
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
        with:
          environment: Preview
          ignore_errors: true
          name: "cleanup-runs"

      - uses: ./actions/exec-task
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
        with:
          environment: Production
          name: "cleanup-runs"
