name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./actions/exec-task
        env:
          TASKS_API_SECRET: ${{ secrets.TASKS_API_SECRET }}
        with:
          environment: Preview
          ignore_errors: true
          name: "cleanup-runs"

      - uses: ./actions/exec-task
        env:
          TASKS_API_SECRET: ${{ secrets.TASKS_API_SECRET }}
        with:
          environment: Production
          name: "cleanup-runs"
