name: e2e

on: deployment_status

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [A, B, C]
    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: npx cypress install
      - uses: ./actions/patch-cypress-config
        with:
          api_url: ${{ github.event.deployment_status.target_url }}
      - run: npx cypress run --record --parallel --ci-build-id=e2e-${{ github.event.deployment_status.id }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.TASKS_API_SECRET }}
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-${{ matrix.container }}
          path: cypress/videos
