name: e2e

on: [push, deployment, deployment_status]

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [A, B, C]

    steps:
      - uses: actions/checkout@v1

      - run: yarn install

      - uses: ./actions/patch-cypress-config
        with:
          api_url: ${{ github.event.deployment_status.target_url }}

      - run: yarn cypress run --record --parallel --key=${{ secrets.CYPRESS_KEY }} --ci-build-id=e2e-${{ github.event.deployment_status.id }}
