name: e2e

on: deployment_status

jobs:
  cypress:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [A, B]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - uses: ./actions/patch-cypress-config
        with:
          api_url: ${{ github.event.deployment_status.target_url }}
      - run: npx cypress run --record --parallel --ci-build-id=cypress-${{ github.event.deployment_status.id }}
        continue-on-error: true
        env:
          DEBUG: "cypress:server:record,cypress:server:api"
          CYPRESS_RECORD_KEY: ${{ secrets.NCD_SECRET }}

  cypress_6-6:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [A, B]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm -D i cypress@6.6
      - run: npm i
      - uses: ./actions/patch-cypress-config
        with:
          api_url: ${{ github.event.deployment_status.target_url }}
      - run: npx cypress run --record --parallel --ci-build-id=cypress@6.6-${{ github.event.deployment_status.id }}
        continue-on-error: true
        env:
          DEBUG: "cypress:server:record,cypress:server:api"
          CYPRESS_RECORD_KEY: ${{ secrets.NCD_SECRET }}
