name: main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn checks
      - run: yarn build:actions
      - run: |
          git add .
          git diff --quiet || exit 1
