name: PR

on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
        with:
          binaries: cypress
      - run: yarn checks

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
        with:
          binaries: cypress
      - run: yarn build
      - run: |
          git add .
          git diff --quiet || exit 1
