name: e2e

on: deployment_status

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: yarn install --force --frozen-lockfile
      - run: yarn test
        env:
          DEPLOY_TARGET_URL: ${{ github.event.deployment_status.target_url }}
